# Generated by Django 3.2.9 on 2021-11-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toy',
            old_name='date',
            new_name='status_update',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='status_updated',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='text',
        ),
        migrations.AlterField(
            model_name='toy',
            name='status',
            field=models.CharField(choices=[('o', 'ok'), ('b', 'broken'), ('r', 'repair')], default='o', max_length=50),
        ),
    ]
