# Generated by Django 3.2.9 on 2021-11-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211106_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='games',
        ),
        migrations.AddField(
            model_name='toy',
            name='games',
            field=models.ManyToManyField(to='app.Game', verbose_name='list of games'),
        ),
    ]
