# Generated by Django 3.2.9 on 2021-11-09 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
